# The modifications of the output file from Kalibr:
# 1. For each matrix (e.g. cam0/T_cam_imu), remove the brackets and minus sign for each line. Use one pair of brackets for each matrix.
# 2. Add the T_imu_body at the end of the calibration file (usually set to identity).
cam0:
  T_cam_imu:
        [0, 1, 0, 0.25,
         0, 0, 1, 0,
         1, 0, 0, 0,
         0, 0, 0, 1]
  camera_model: pinhole
  distortion_coeffs: [0,  0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [1, 1, 0, 0]
  resolution: [1280, 560]
  timeshift_cam_imu: 0.0
cam1:
  T_cam_imu:
        [0, 1, 0, -0.25,
         0, 0, 1, 0,
         1, 0, 0, 0,
         0, 0, 0, 1]
  T_cn_cnm1:
        [1, 0, 0, -0.5,
         0, 1, 0, 0,
         0, 0, 1, 0,
         0, 0, 0, 1]
  camera_model: pinhole
  distortion_coeffs: [0,  0, 0, 0, 0]
  distortion_model: radtan
  intrinsics: [1, 1, 0, 0]
  resolution: [1280, 560]
  timeshift_cam_imu: 0.0
T_imu_body:
  [1.0000, 0.0000, 0.0000, 0.0000,
  0.0000, 1.0000, 0.0000, 0.0000,
  0.0000, 0.0000, 1.0000, 0.0000,
  0.0000, 0.0000, 0.0000, 1.0000]

